/**
 * The call *history* against Postgres. The negotiation never touches the database
 * — that rides broadcast in services/callSignal.ts.
 */
import { upsertCall } from '../db/calls';
import { memberIds } from '../db/members';
import type { CallKind, CallStatus } from './calls';
import { isSupabaseConfigured, supabase } from './supabase';

/**
 * `connecting` is a client-side distinction — the callee has answered but media is
 * still negotiating. Postgres only knows the five outcomes a history row can have.
 */
function serverStatus(status: CallStatus): string {
  return status === 'connecting' ? 'ringing' : status;
}

/**
 * The id is generated by the caller and used on both sides, so the two devices and
 * the row all agree on which call this is without a round trip first.
 */
export async function createCallRow(input: {
  callId: string;
  chatId: string;
  initiatorId: string;
  kind: CallKind;
}): Promise<void> {
  if (!isSupabaseConfigured) return;

  const { error } = await supabase.from('calls').insert({
    id: input.callId,
    chat_id: input.chatId,
    initiator_id: input.initiatorId,
    kind: input.kind,
    status: 'ringing',
  });
  if (error) throw error;
}

export async function updateCallRow(
  callId: string,
  patch: { status?: CallStatus; answeredAt?: number; endedAt?: number },
): Promise<void> {
  if (!isSupabaseConfigured) return;

  const update: Record<string, unknown> = {};
  if (patch.status) update.status = serverStatus(patch.status);
  if (patch.answeredAt) update.answered_at = new Date(patch.answeredAt).toISOString();
  if (patch.endedAt) update.ended_at = new Date(patch.endedAt).toISOString();
  if (Object.keys(update).length === 0) return;

  const { error } = await supabase.from('calls').update(update).eq('id', callId);
  if (error) throw error;
}

type CallRowFromServer = {
  id: string;
  chat_id: string;
  initiator_id: string;
  kind: string;
  status: string;
  started_at: string;
  answered_at: string | null;
  ended_at: string | null;
};

/**
 * Pulls history for every chat the viewer belongs to — RLS already restricts the
 * select to those.
 *
 * The peer is derived from local membership rather than fetched: the history row
 * knows the chat, and for a direct chat the other member *is* the peer. A group
 * call's peer is the initiator, which is the name that belongs on the row.
 */
export async function pullCallHistory(viewerId: string, limit = 100): Promise<void> {
  if (!isSupabaseConfigured) return;

  const { data, error } = await supabase
    .from('calls')
    .select('id, chat_id, initiator_id, kind, status, started_at, answered_at, ended_at')
    .order('started_at', { ascending: false })
    .limit(limit);

  if (error) throw error;

  for (const row of (data ?? []) as CallRowFromServer[]) {
    const outgoing = row.initiator_id === viewerId;
    const members = memberIds(row.chat_id);
    const peerId = outgoing
      ? (members.find((userId) => userId !== viewerId) ?? row.initiator_id)
      : row.initiator_id;

    upsertCall({
      id: row.id,
      chatId: row.chat_id,
      peerId,
      kind: row.kind as CallKind,
      direction: outgoing ? 'outgoing' : 'incoming',
      status: row.status as CallStatus,
      startedAt: new Date(row.started_at).getTime(),
      answeredAt: row.answered_at ? new Date(row.answered_at).getTime() : null,
      endedAt: row.ended_at ? new Date(row.ended_at).getTime() : null,
    });
  }
}
